---
title: "STAT651-Project"
author: "Dan Hoang_cu2107"
date: "`r Sys.Date()`"
format: pdf
editor: visual
---

## 

```{r, warning=FALSE, message=FALSE}
library(pacman)
p_load("tidyverse", "ggplot2", "readxl", "socviz", "statebins", "maps", "ggthemes")
```

# Job Posting on Indeed 2020 - 2022

```{r}
indeedJob <- read_csv("indeedJob.csv")
head(indeedJob)
```

```{r}
us_states <- map_data("state")
indeedJob$region <- tolower(indeedJob$state)
us_indeedJob <- left_join(us_states, indeedJob)
```

```{r, fig.height = 4, fig.width = 7}
ggplot(indeedJob, aes(state=state, fill=average_jobpost)) +
  geom_statebins() +labs(fill = "Percent Change") + scale_fill_gradient(low = "white", high = "#69b3a2") 
```

```{r, fig.height = 6, fig.width = 8}
p0 <- ggplot(data = us_indeedJob,
             mapping = aes(x = long, y = lat, group = group, fill = average_jobpost))

p1 <- p0 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) 
p2 <- p1 + scale_fill_gradient(low = "white", high = "#69b3a2") +
        labs(title = "Job Posting on Indeed 2020-2022") 
p2 + labs(fill = "Percent Change") + theme_map()
```

\newpage

# GDP Computer and Electronic Product Manufacturing 2021

```{r}
GDPComputer <- read_csv("GDPComputer.csv")
head(GDPComputer)
```

```{r}
us_states1 <- map_data("state")
GDPComputer$region <- tolower(GDPComputer$state)
us_GDPComputer <- left_join(us_states1, GDPComputer)
```

```{r, fig.height = 4, fig.width = 7}
ggplot(GDPComputer, aes(state=state, fill=gdp)) +
  geom_statebins()  + scale_fill_gradient(low = "white", high = "#69b3a2") 
```

```{r, fig.height = 6, fig.width = 8}
p0 <- ggplot(data = us_GDPComputer,
             mapping = aes(x = long, y = lat, group = group, fill = gdp))

p1 <- p0 + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) 
p2 <- p1 + scale_fill_gradient(low = "white", high = "#69b3a2") +
        labs(title = "GDP Computer and Electronic Product Manufacturing 2021") 
p2 + labs(fill = "Milions of Chained")  + theme_map()
```
